const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 570,
      brand: 'Ayiyappa',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A ultra popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 180,
      brand: 'VIP',
      rating: 3.5,
      numReviews: 70,
      countInStock: 20,
      description: 'A newly popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 740,
      brand: 'Vimal',
      rating: 4.2,
      numReviews: 310,
      countInStock: 50,
      description: 'A potentially popular shirt',
    },
    {
      name: 'Summer Pants',
      slug: 'summer-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 790,
      brand: 'Thukaram',
      rating: 4.5,
      numReviews: 50,
      countInStock: 80,
      description: 'A fully popular pant',
    },
    {
      name: 'Loose Pants',
      slug: 'loose-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 590,
      brand: 'Thukaram',
      rating: 4.9,
      numReviews: 150,
      countInStock: 80,
      description: 'A greatly  popular pant',
    },
    {
      name: 'Winter Pants',
      slug: 'winter-pants',
      category: 'Pants',
      image: '/images/Pants3.jpg',
      price: 720,
      brand: 'Reymands',
      rating: 4.0,
      numReviews: 80,
      countInStock: 80,
      description: 'A important popular Pant',
    },
  ],
}

export default data
